language: cpp

compiler:
  - clang
  - gcc

os:
  - linux

dist: xenial

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-all-dev -y
  - wget https://github.com/msgpack/msgpack-c/archive/cpp-3.1.1.zip
  - unzip cpp-3.1.1.zip
  - cd msgpack-c-cpp-3.1.1
  - mkdir build
  - cd build
  - cmake -DMSGPACK_CXX17=ON ..
  - make
  - sudo make install

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
