language: cpp

compiler:
  - clang
  - gcc

os:
  - linux

dist: xenial

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-all-dev -y

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
