language: cpp

compiler:
  - clang
  - gcc

os:
  - linux

dist: xenial

before_install:
  - wget https://dl.bintray.com/boostorg/release/1.69.0/source/boost_1_69_0.tar.gz
  - tar xf boost_1_69_0.tar.gz
  - cd boost_1_69_0
  - ./bootstrap.sh
  - sudo ./b2 -d0 --without-atomic --without-chrono --without-container --without-context --without-contract --without-coroutine --without-date_time --without-exception --without-fiber --without-filesystem --without-graph --without-graph_parallel --without-iostreams --without-locale --without-log --without-math --without-mpi --without-program_options --without-python --without-random --without-regex --without-serialization --without-stacktrace --without-test --without-thread --without-timer --without-type_erasure --without-wave variant=release link=static threading=multi runtime-link=static install
  - cd ..
  - wget https://github.com/msgpack/msgpack-c/archive/cpp-3.1.1.zip
  - unzip cpp-3.1.1.zip
  - cd msgpack-c-cpp-3.1.1
  - mkdir build
  - cd build
  - cmake -DMSGPACK_CXX11=ON ..
  - make
  - sudo make install
  - cd ../..

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
