import os

from conan import ConanFile
from conan.tools.build import check_min_cppstd
from conan.tools.cmake import CMake, CMakeDeps, CMakeToolchain, cmake_layout
from conan.tools.files import copy, rmdir


class RemoteConan(ConanFile):
    name = "remote"
    version = "0.2.0"
    license = "MIT"
    url = "https://github.com/polaris/remote"
    description = "Typed msgpack-rpc for C++20, built on Boost.Asio coroutines"
    topics = ("rpc", "msgpack", "msgpack-rpc", "asio", "coroutines", "networking")
    package_type = "static-library"
    settings = "os", "arch", "compiler", "build_type"
    options = {"fPIC": [True, False]}
    default_options = {
        "fPIC": True,
        # remote uses only header-only parts of Boost.
        "boost/*:header_only": True,
    }
    exports_sources = "CMakeLists.txt", "LICENSE", "cmake/*", "include/*", "src/*", "tests/*", "examples/*"

    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC

    def validate(self):
        check_min_cppstd(self, 20)

    def requirements(self):
        self.requires("boost/1.91.0", transitive_headers=True)
        self.requires("msgpack-cxx/7.0.0", transitive_headers=True)

    def build_requirements(self):
        self.test_requires("catch2/3.16.0")

    def layout(self):
        cmake_layout(self)

    def generate(self):
        CMakeDeps(self).generate()
        toolchain = CMakeToolchain(self)
        toolchain.cache_variables["REMOTE_BUILD_TESTS"] = not self.conf.get("tools.build:skip_test", default=False)
        toolchain.cache_variables["REMOTE_BUILD_EXAMPLES"] = True
        toolchain.generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
        if not self.conf.get("tools.build:skip_test", default=False):
            cmake.test()

    def package(self):
        copy(self, "LICENSE", self.source_folder, os.path.join(self.package_folder, "licenses"))
        CMake(self).install()
        # Consumers get the CMake config generated by Conan instead.
        rmdir(self, os.path.join(self.package_folder, "lib", "cmake"))

    def package_info(self):
        self.cpp_info.set_property("cmake_file_name", "remote")
        self.cpp_info.set_property("cmake_target_name", "remote::remote")
        self.cpp_info.libs = ["remote"]
        self.cpp_info.requires = ["boost::headers", "msgpack-cxx::msgpack-cxx"]
        if self.settings.os in ("Linux", "FreeBSD"):
            self.cpp_info.system_libs = ["pthread"]
